In [42]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE, RFECV

In [43]:
data = pd.read_csv("C:\\Users\\Aravinthan\\Desktop\\MLO\\data\\Boston.CSV")

In [44]:
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio   black  lstat  medv
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7  396.90   5.33  36.2

In [45]:
x = data.iloc[:,:12]
y = data.iloc[:,12]

In [46]:
model = LinearRegression()

In [47]:
rfe = RFE(estimator=model,n_features_to_select=7)

In [48]:
results.n_features_

np.int64(7)

In [49]:
results.support_

array([ True, False, False,  True,  True, False,  True,  True, False,
        True, False,  True])

In [50]:
selected = x.columns[results.support_]  #Boolean Masking
selected

Index(['crim', 'nox', 'rm', 'dis', 'rad', 'ptratio', 'lstat'], dtype='object')

In [38]:
x_new = x[selected]
x_new = x_new.values
x_new

array([[6.3200e-03, 5.3800e-01, 6.5750e+00, ..., 1.0000e+00, 1.5300e+01,
        4.9800e+00],
       [2.7310e-02, 4.6900e-01, 6.4210e+00, ..., 2.0000e+00, 1.7800e+01,
        9.1400e+00],
       [2.7290e-02, 4.6900e-01, 7.1850e+00, ..., 2.0000e+00, 1.7800e+01,
        4.0300e+00],
       ...,
       [6.0760e-02, 5.7300e-01, 6.9760e+00, ..., 1.0000e+00, 2.1000e+01,
        5.6400e+00],
       [1.0959e-01, 5.7300e-01, 6.7940e+00, ..., 1.0000e+00, 2.1000e+01,
        6.4800e+00],
       [4.7410e-02, 5.7300e-01, 6.0300e+00, ..., 1.0000e+00, 2.1000e+01,
        7.8800e+00]])

In [39]:
##Direct Method

In [40]:
x_new1 = rfe.fit_transform(x,y)
x_new1

array([[6.3200e-03, 5.3800e-01, 6.5750e+00, ..., 1.0000e+00, 1.5300e+01,
        4.9800e+00],
       [2.7310e-02, 4.6900e-01, 6.4210e+00, ..., 2.0000e+00, 1.7800e+01,
        9.1400e+00],
       [2.7290e-02, 4.6900e-01, 7.1850e+00, ..., 2.0000e+00, 1.7800e+01,
        4.0300e+00],
       ...,
       [6.0760e-02, 5.7300e-01, 6.9760e+00, ..., 1.0000e+00, 2.1000e+01,
        5.6400e+00],
       [1.0959e-01, 5.7300e-01, 6.7940e+00, ..., 1.0000e+00, 2.1000e+01,
        6.4800e+00],
       [4.7410e-02, 5.7300e-01, 6.0300e+00, ..., 1.0000e+00, 2.1000e+01,
        7.8800e+00]])

In [41]:
results.ranking_

array([1, 3, 2, 1, 1, 6, 1, 1, 4, 1, 5, 1])

In [52]:
#New Method - RFECV

In [53]:
rfecv = RFECV(estimator=model,min_features_to_select=1,cv=10)

In [54]:
results1 = rfecv.fit(x,y)

In [56]:
results1.support_

array([False, False, False,  True,  True, False,  True, False, False,
        True, False,  True])

In [57]:
x.columns[results1.support_]

Index(['nox', 'rm', 'dis', 'ptratio', 'lstat'], dtype='object')

In [58]:
x[x.columns[results1.support_]].values

array([[ 0.538 ,  6.575 ,  4.09  , 15.3   ,  4.98  ],
       [ 0.469 ,  6.421 ,  4.9671, 17.8   ,  9.14  ],
       [ 0.469 ,  7.185 ,  4.9671, 17.8   ,  4.03  ],
       ...,
       [ 0.573 ,  6.976 ,  2.1675, 21.    ,  5.64  ],
       [ 0.573 ,  6.794 ,  2.3889, 21.    ,  6.48  ],
       [ 0.573 ,  6.03  ,  2.505 , 21.    ,  7.88  ]])

In [59]:
x_new2 = rfecv.fit_transform(x,y)

In [60]:
x_new2

array([[ 0.538 ,  6.575 ,  4.09  , 15.3   ,  4.98  ],
       [ 0.469 ,  6.421 ,  4.9671, 17.8   ,  9.14  ],
       [ 0.469 ,  7.185 ,  4.9671, 17.8   ,  4.03  ],
       ...,
       [ 0.573 ,  6.976 ,  2.1675, 21.    ,  5.64  ],
       [ 0.573 ,  6.794 ,  2.3889, 21.    ,  6.48  ],
       [ 0.573 ,  6.03  ,  2.505 , 21.    ,  7.88  ]])